apiVersion: batch/v1
kind: Job
metadata:
  name: random-string 
spec:
  parallelism: 2
  completions: 2 
  template:
    spec:
      containers:
      - name: random-string
        image: python
        command: ["python","-c", "'import random, string; print(''.join(random.SystemRandom().choice(string.ascii_lowercase + string.ascii_uppercase + string.digits) for _ in range(20)))'"]
      restartPolicy: Never
